name: Build and release

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v1
      -
        name: vuepress-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          CNAME: asset-building.labor.tools
          ACCESS_TOKEN: ${{ secrets.ACTIONS_DEPLOY_TOKEN }}
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: cd docs && npm i && npm run build
          BUILD_DIR: .vuepress/dist/
  build:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v1
      -
        uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      -
        name: Installing npm modules
        run: npm install
      -
        name: Build library
        run: npm run build
      -
        name: Create Changelog and bump release version
        uses: labor-digital/conventional-release-action@master
        with:
          github-token: ${{ secrets.github_token }}
      -
        name: Publish library on npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

